### ISSUE TITLE
Element queries on ember

### ISSUE THREAD

**Issue by scooterlord** [tomhodgins/element-queries-spec#1]
please delete me! sorry :(

**Comment by tomhodgins** [comment]
Hi @scooterlord! I think you're referring to the [EQCSS.js](https://github.com/eqcss/eqcss) plugin?

The 'lazy' technique in the code I think you're referring to is the [EQCSS.throttle() function](https://github.com/eqcss/eqcss/blob/gh-pages/EQCSS.js#L887) which ensures the styles are not recalculated more frequently than every 200ms.

You are able to bypass this wait time by invoking `EQCSS.apply()` manually from JavaScript at any time to trigger an instant recalculation of the rules!
