### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by AndiLeni** [tomhodgins/element-queries-spec#7]
Hello,
I want to know whether this project is ready to be used in production or not.

**Comment by tomhodgins** [comment]
Hi @AndiLeni! This repository is an unofficial spec describing a lot of the features included in [EQCSS](https://github.com/eqcss/eqcss).

If you're looking for a production-ready implementation EQCSS does everything in the spec plus more, and there are some other tools like [eqcss-parse](https://www.npmjs.com/package/eqcss-parse) that can help you with your workflow (depending on how you want to use it). The simplest way is just pulling in EQCSS like this:

```html
<div>Hello</div>

<style>
  @element div and (min-width: 600px) {
    $this {
      background: lime;
    }
  }
</style>

<script src=http://elementqueries.com/EQCSS.js></script>
```

**Comment by tomhodgins** [comment]
You can also check out some EQCSS demos on Codepen to see examples of the syntax in use: [EQCSS pens on Codepen](https://codepen.io/search/pens?q=eqcss&limit=all&order=popularity&depth=everything&show_forks=false)

**Comment by AndiLeni** [comment]
Based on you answer I guess it's ready for production. Thanks!
